### ISSUE TITLE
Как установить этот плагин?

### ISSUE THREAD

**Issue by khmelev77** [vahelce/vroleplay#3]
Здравствуйте.
Сайт https://spigotmc.ru/resources/vroleplay-prostoj-plagin-dlja-otygrovki-rp-situacij.186/ сейчас не работает нормально, объясните пожалуйста, как ваш исходный код превратить в плагин (.jar)?

**Comment by vahelce** [comment]
> Здравствуйте.
> Сайт https://spigotmc.ru/resources/vroleplay-prostoj-plagin-dlja-otygrovki-rp-situacij.186/ сейчас не работает нормально, объясните пожалуйста, как ваш исходный код превратить в плагин (.jar)?


Сайт доступен снова. В конфигурации есть одна ошибка, ее нужно будет поправить. 

Готовый релиз можно загрузить здесь: https://github.com/vahelce/vroleplay/releases

Если Вы хотите собрать плагин самостоятельно, Вам нужно будет загрузить JDK и исходный код плагина, распаковать его в любое место и запустить в терминале команду gradle build. Затем по пути {папка_куда_Вы_распокавали_код}/build/libs можно будет забрать готовый файл.
